# Generated by Django 4.2 on 2025-05-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='counted_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
