# Generated by Django 4.2 on 2025-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_services_counted_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='total_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
