# Generated by Django 4.2 on 2025-04-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='pricing',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
