# Generated by Django 4.2 on 2025-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_items_options_alter_pricing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='root.items'),
        ),
    ]
